version: "3.9"

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
